web/config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :projectusers
  end

  root 'projects#index'

end

web/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :projectusers, dependent: :destroy

  # def as_json(options = {})
  #   super(options.merge(:include => :projectusers))
  # end
end

web/app/models/projectuser.rb
class Projectuser < ActiveRecord::Base
  belongs_to :project
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

web/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  http_basic_authenticate_with name: "wangyan", password: "wangyan", except: [:index]

  respond_to :json, :html

  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def show
    @project = Project.find(params[:id])
    respond_with(@project , include: :projectusers)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :url, :path)
  end
end

web/app/controllers/projectusers_controller.rb
class ProjectusersController < ApplicationController

  http_basic_authenticate_with name: "wangyan", password: "wangyan", only: [:destroy, :create]

  def create
    @project = Project.find(params[:project_id])
    @user = @project.projectusers.create(user_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:project_id])
    @user = @project.projectusers.find(params[:id])
    @user.destroy
    redirect_to project_path(@project)
  end

  private
  def user_params
    params.require(:projectuser).permit(:name, :password)
  end

end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/projects_helper.rb
module ProjectsHelper
end

web/app/helpers/projectusers_helper.rb
module ProjectusersHelper
end

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

web/app/views/projects/_form.html.erb
<%= form_for @project  do |f| %>

    <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :url %> <br/>
      <%= f.text_field :url %>
    </p>
    <p>
      <%= f.label :path %> <br/>
      <%= f.text_field :path %>
    </p>
    <%= f.submit %>
<% end %>

web/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Back', project_path %>

web/app/views/projects/index.html.erb
<h1>Projects</h1>

<%= link_to 'new project', new_project_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Path</th>
    <th colspan="3"></th>
  </tr>
  <%= @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.url %></td>
        <td><%= project.path %></td>
        <td><%= link_to 'Show', project_path(project) %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

web/app/views/projects/new.html.erb
<h1>new project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

web/app/views/projects/show.html.erb
<p>
  <stong>Name:</stong>
  <%= @project.name %>
</p>
<p>
  <stong>Url:</stong>
  <%= @project.url %>
</p>
<p>
  <stong>Path:</stong>
  <%= @project.name %>
</p>

<h2>Users</h2>
<%= render @project.projectusers %>

<h2>Add a user:</h2>
<%= render "projectusers/form" %>

<%= link_to 'Back', projects_path %> | <%= link_to 'Edit', edit_project_path(@project) %>

web/app/views/projectusers/_form.html.erb
<%= form_for([@project, @project.projectusers.build]) do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.text_field :password %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

web/app/views/projectusers/_projectuser.html.erb
<p>
  <strong>Name:</strong>
  <%= projectuser.name %>
</p>
<p>
  <strong>Password:</strong>
  <%= projectuser.password %>
</p>

<p>
  <%= link_to 'Destroy User', [projectuser.project, projectuser],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>